### ISSUE TITLE
Switching to InnoDB I/O Info mode causes crash

### ISSUE THREAD

**Issue by selftaught** [innotop/innotop#127] opened 2015-12-22 23:13 UTC
innotop  Ver 1.10.0
mysqld  Ver 10.1.9-MariaDB for Linux on x86_64 (MariaDB Server)
CentOS Linux release 7.2.1511 (Core) 

When I run innotop then switch to InnoDB I/O Info mode with the "I" key, the program dies and gives this perl error: `Use of uninitialized value $text in pattern match (m//) at /usr/bin/innotop line 620.`

which is this sub routine:

```perl
sub parse_innodb_timestamp {
   my $text = shift;
   my ( $y, $m, $d, $h, $i, $s )
      = $text =~ m/^(\d\d)(\d\d)(\d\d) +(\d+):(\d+):(\d+)$/;
   die("Can't get timestamp from $text\n") unless $y;
   $y += 2000; 
   return ( $y, $m, $d, $h, $i, $s ); 
}
```

which is called by `sub parse_status_text`.

in these two lines:

`( $time_text ) = $fulltext =~ m/^$s INNODB MONITOR OUTPUT$/m;
      $innodb_data{'ts'} = [ parse_innodb_timestamp( $time_text ) ];`

the regex on the first line equates to `^/(\d{6} .?\d:\d\d:\d\d) INNODB MONITOR OUTPUT$/m`

however, this regex doesn't successfully parse the timestamp from the InnoDB header in $fulltext.

the header is `2015-12-22 17:33:47 7f91433b2700 INNODB MONITOR OUTPUT`

not sure what the hash `7f91433b2700` represents but the regex isn't matching because of it.

**Comment by quanah** [comment] 2015-12-22 23:19
It is generally considered best practice to review open bugs first.  If you did that, you'd find issue#124, which fixes innotop to work with mariadb 10.1.x

**Comment by selftaught** [comment] 2015-12-22 23:25
Ah, damn. I should've opened each and looked over them closer. I looked at the list of 18 but missed it because I only looked at the titles. I'll look more thoroughly next time. Thanks @quanah.

**Comment by quanah** [comment] 2016-01-04 21:30
Can you close this one as a dupe? :)

**Comment by lefred** [comment] 2016-02-01 09:36
duplicate of #124

**Closed by lefred** 2016-02-01 09:36 UTC
